GET http://localhost:5050/posts

#####
POST http://localhost:5050/posts HTTP/1.1
Content-Type: application/json

{
    "category": "fantasy",
    "title": "Titolo post 2",
    "cover": "https://picsum.photos/500/300",
    "readTime": {
        "value": 30,
        "unit": "minutes"
    },
    "author": {
        "name": "Matteo",
        "avatar": "https://picsum.photos/100/100"
    },
    "content": "Lorem ipsum dolor sit amet..."
}

######
GET http://localhost:5050/posts/64ac567d681ad5311083979a

######
PATCH http://localhost:5050/posts/64ac567d681ad5311083979a HTTP/1.1
Content-Type: application/json

{
    "content": "contenuto nuovo"
}

#######
DELETE http://localhost:5050/posts/64ac567d681ad5311083979a